# Generated by Django 5.2.13 on 2026-04-30 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=255)),
                ("company_website", models.URLField(blank=True)),
                ("role_title", models.CharField(max_length=255)),
                ("role_location", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("y_combinator", "Y Combinator"),
                            ("linkedin", "LinkedIn"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("applied", "Applied"),
                            ("in_review", "In Review"),
                            ("interview", "Interview"),
                            ("rejected", "Rejected"),
                            ("offer", "Offer"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("application_payload", models.JSONField(blank=True, default=dict)),
                ("response_summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_status_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_status_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="resumes/")),
                ("parsed_text", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutreachMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_name", models.CharField(max_length=255)),
                (
                    "recipient_email",
                    models.EmailField(blank=True, db_index=True, max_length=254),
                ),
                ("recipient_linkedin_url", models.URLField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("linkedin", "LinkedIn")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("replied", "Replied"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "response_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outreach_messages",
                        to="users.jobapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outreach_messages",
                        to="users.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="users.resume",
            ),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_job_titles", models.JSONField(blank=True, default=list)),
                ("target_locations", models.JSONField(blank=True, default=list)),
                ("target_companies", models.JSONField(blank=True, default=list)),
                ("target_sources", models.JSONField(blank=True, default=list)),
                ("auto_apply", models.BooleanField(default=False)),
                ("auto_email", models.BooleanField(default=False)),
                ("linkedin_outreach", models.BooleanField(default=False)),
                ("weekly_digest", models.BooleanField(default=True)),
                (
                    "default_resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_for",
                        to="users.resume",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoogleIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "google_sub",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("avatar_url", models.URLField(blank=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_scope", models.TextField(blank=True)),
                (
                    "token_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_login_at"], name="google_last_login_idx"
                    ),
                    models.Index(
                        fields=["token_expires_at"], name="google_token_exp_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(db_index=True, max_length=20)),
                ("new_status", models.CharField(db_index=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="users.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "-created_at"],
                        name="appstatus_app_created_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["user", "is_primary"], name="resume_user_primary_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["user", "-created_at"], name="resume_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outreachmessage",
            index=models.Index(
                fields=["user", "status"], name="outreach_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outreachmessage",
            index=models.Index(
                fields=["user", "channel"], name="outreach_user_channel_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outreachmessage",
            index=models.Index(
                fields=["channel", "status"], name="outreach_channel_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outreachmessage",
            index=models.Index(
                fields=["sent_at", "status"], name="outreach_sent_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "status"], name="jobapp_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "-created_at"], name="jobapp_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["source", "-created_at"], name="jobapp_source_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "-applied_at"], name="jobapp_status_applied_idx"
            ),
        ),
    ]
