# Generated by Django 5.2.13 on 2026-04-30 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="resume",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="s3_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="s3_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploading", "Uploading"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["user", "upload_status"], name="resume_user_upload_idx"
            ),
        ),
    ]
